# https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

github: vorburger
patreon: vorburger
open_collective: vorburger
ko_fi: vorburger
tidelift: maven/ch.vorburger.mariaDB4j
community_bridge: MariaDB4j
liberapay: vorburger
issuehunt: vorburger
otechie: # Replace with a single Otechie username
custom: https://www.paypal.me/MichaelVorburgerCH
